version: "3.8"
   
services:
  web:
    build: ./client
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build: ./server
    image: server
    command: gunicorn --bind 0.0.0.0:8888 server.wsgi
    env_file: ./server/.env
    links:
      - db:db
    volumes:
      - .:/code
    networks:
      - api-network
      - db-network
    depends_on:
      - db
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./server:/etc/nginx/conf.d/
      - ./server/static:/usr/share/nginx/html/static/
    ports:
      - 8000:8000
    networks:
      - api-network
    depends_on:
      - api 
  # migration:
  #   image: server
  #   command: python scripts/init.py
  #   env_file: ./server/.env
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     db:
  #       condition: service_healthy
  db:
    container_name: db
    image: postgres:10-alpine
    restart: always
    #env_file:
    #  - ./server/.env
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-network
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -U postgres"]
    #  interval: 5s
    #  timeout: 5s
    #  retries: 5

networks:
  api-network:
  db-network:
