version: "3.8"
   
services:
  db:
    image: nouchka/sqlite3
  api:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    build: ./client
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - api
