version: "3.8"
   
services:
  db:
    image: nouchka/sqlite3
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./:/var/www
      - ./server:/etc/nginx/conf.d/
      - ./server/static:/usr/share/nginx/html/static/
    ports:
      - 8000:8000
    networks:
      - api-network
    depends_on:
      - api 
  api:
    build: ./server
    image: server
    command: gunicorn --bind 0.0.0.0:8888 server.wsgi
    env_file: ./server/.env
    volumes:
      - .:/code
    networks:
      - api-network
    depends_on:
      - db
      - migration
  # add an api_init dependency that runs collectstatic, migrate and createsuperuser
  web:
    build: ./client
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - api

networks:
  api-network: